try {
    throw ValidationError("test")
} catch (error) {
    msg = error.message
}